args:
  RPMAX: 10
  clientNum: 3
  cuda: 0
  dataset: cora
  dir_name: cora_GCN_c3_seed0
  dropout: 0.5
  early_stopping: 200
  epochs: 1000
  hidden: 32
  institueion_idx: null
  institution_name: cora-global
  localIndex: null
  lr: 0.01
  neighborAgencyNum: 0
  net: GCN
  print_freq: 20
  runTag: -1
  seed: 0
  train_rate: 0.6
  val_rate: 0.2
  weight_decay: 0.0001
sub_acc:
- 0.8628472222222222
- 0.75
- 0.9047619047619048
test_acc: 0.8620689655172413
val_acc: 0.8523985239852399
val_loss: 0.43374165892601013
