args:
  RPMAX: 10
  clientNum: 3
  cuda: 0
  dataset: cora
  dir_name: cora_GCN_c3_seed0
  dropout: 0.5
  early_stopping: 200
  epochs: 1000
  hidden: 32
  institueion_idx: 0
  institution_name: cora-subA
  localIndex: 2555
  lr: 0.005
  neighborAgencyNum: 0
  net: GCN
  print_freq: 20
  runTag: -1
  seed: 0
  train_rate: 0.6
  val_rate: 0.2
  weight_decay: 0.0001
test_acc: 0.880672268907563
val_acc: 0.8825831702544031
val_loss: 0.4360194802284241
